# Generated by Django 5.1.3 on 2024-12-14 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_quiz", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="roomId",
            new_name="room_id",
        ),
    ]
