# Generated by Django 5.1.3 on 2024-12-14 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_quiz", "0002_remove_guestuser_room"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="guest_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="users.guestuser",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_rooms",
                to="users.user",
            ),
        ),
        migrations.DeleteModel(
            name="GuestUser",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
