# Generated by Django 5.1.4 on 2024-12-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_quiz", "0005_alter_topic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(default="easy", max_length=10),
        ),
        migrations.AddField(
            model_name="singleplayerquestion",
            name="difficulty",
            field=models.CharField(default="easy", max_length=10),
        ),
    ]
