# Generated by Django 5.1.4 on 2025-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_quiz", "0008_participant_avatar_seed_participant_avatar_style_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="avatar_seed",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="avatar_style",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
