# Generated by Django 5.1.4 on 2025-01-02 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_quiz", "0009_alter_participant_avatar_seed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="timer",
            new_name="time_per_question",
        ),
    ]
