# Generated by Django 5.1.4 on 2025-01-02 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_quiz", "0010_rename_timer_question_time_per_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="correct_answers",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="score",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="skipped_questions",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="wrong_answers",
        ),
    ]
