# Generated by Django 5.1.3 on 2024-12-03 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='join_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
